# This workflow uses Garak Security Scanner to detect AI vulnerabilities
# Documentation: https://github.com/garaksecurity/garak-security-scanner
# Configure the required secrets in your repository settings:
# - GARAK_API_KEY: Your Garak API key (get one at https://app.garak.ai)
# - X_API_KEY: API key for the endpoint you're testing (e.g., Anthropic, OpenAI)

name: Garak AI Security Scan

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  garak-security-scan:
    runs-on: ubuntu-latest
    name: Garak AI Security Analysis

    permissions:
      contents: read
      pull-requests: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Garak Security Scanner
        id: garak_scan
        uses: garaksecurity/garak-security-scanner@v1
        with:
          api_key: ${{ secrets.GARAK_API_KEY }}
          endpoint: https://api.anthropic.com/v1/messages
          target_api_key: ${{ secrets.X_API_KEY }}
          probes: dan,security,privacy,toxicity,hallucination,performance,robustness,ethics,stereotypes
          generator_mode: rest
          parallel_attempts: 4
          response_json_path: $.content[0].text
          timeout_minutes: 60
          score_threshold: 80
          poll_interval: 10

      - name: Display scan results
        if: always()
        run: |
          echo "## 🛡️ Garak Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Scan ID:** ${{ steps.garak_scan.outputs.scan_id }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Security Score:** ${{ steps.garak_scan.outputs.security_score }}/100" >> $GITHUB_STEP_SUMMARY
          echo "- **Vulnerabilities Found:** ${{ steps.garak_scan.outputs.vulnerabilities_found }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ steps.garak_scan.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[📊 View Full Report](${{ steps.garak_scan.outputs.report_url }})" >> $GITHUB_STEP_SUMMARY

      - name: Upload scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: garak-security-report
          path: garak-report-*.json
          retention-days: 30

      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ steps.garak_scan.outputs.status }}';
            const score = '${{ steps.garak_scan.outputs.security_score }}';
            const vulns = '${{ steps.garak_scan.outputs.vulnerabilities_found }}';
            const reportUrl = '${{ steps.garak_scan.outputs.report_url }}';

            const emoji = status === 'passed' ? '✅' : '❌';
            const statusText = status === 'passed' ? 'PASSED' : 'FAILED';

            const body = `## ${emoji} Garak Security Scan ${statusText}

            | Metric | Value |
            |--------|-------|
            | Security Score | **${score}/100** |
            | Vulnerabilities | ${vulns} |
            | Status | ${statusText} |

            ${reportUrl ? `[📊 View Detailed Report](${reportUrl})` : ''}

            ${status === 'failed' ? '⚠️ **Action Required:** Security score below threshold. Please review the vulnerabilities.' : ''}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
